-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MixColumns is
port (
    ap_ready : OUT STD_LOGIC;
    state_0_0_read : IN STD_LOGIC_VECTOR (7 downto 0);
    state_0_1_read : IN STD_LOGIC_VECTOR (7 downto 0);
    state_0_2_read : IN STD_LOGIC_VECTOR (7 downto 0);
    state_0_3_read : IN STD_LOGIC_VECTOR (7 downto 0);
    state_1_0_read : IN STD_LOGIC_VECTOR (7 downto 0);
    state_1_1_read : IN STD_LOGIC_VECTOR (7 downto 0);
    state_1_2_read : IN STD_LOGIC_VECTOR (7 downto 0);
    state_1_3_read : IN STD_LOGIC_VECTOR (7 downto 0);
    state_2_0_read : IN STD_LOGIC_VECTOR (7 downto 0);
    state_2_1_read : IN STD_LOGIC_VECTOR (7 downto 0);
    state_2_2_read : IN STD_LOGIC_VECTOR (7 downto 0);
    state_2_3_read : IN STD_LOGIC_VECTOR (7 downto 0);
    state_3_0_read : IN STD_LOGIC_VECTOR (7 downto 0);
    state_3_1_read : IN STD_LOGIC_VECTOR (7 downto 0);
    state_3_2_read : IN STD_LOGIC_VECTOR (7 downto 0);
    state_3_3_read : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of MixColumns is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv8_1B : STD_LOGIC_VECTOR (7 downto 0) := "00011011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal xor_ln323_fu_142_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_172_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln309_fu_180_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln309_fu_166_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Tm_2_fu_154_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln329_1_fu_194_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln329_fu_188_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Tm_1_fu_148_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_212_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln309_1_fu_220_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln309_1_fu_206_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln330_1_fu_234_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln330_fu_228_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_252_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln309_2_fu_260_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln309_2_fu_246_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln331_1_fu_274_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln331_fu_268_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Tm_3_fu_160_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_292_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln309_3_fu_300_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln309_3_fu_286_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln332_1_fu_314_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln332_fu_308_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln323_1_fu_326_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_356_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln309_4_fu_364_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln309_4_fu_350_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Tm_2_1_fu_338_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln329_4_fu_378_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln329_3_fu_372_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Tm_1_1_fu_332_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_396_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln309_5_fu_404_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln309_5_fu_390_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln330_4_fu_418_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln330_3_fu_412_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_436_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln309_6_fu_444_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln309_6_fu_430_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln331_4_fu_458_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln331_3_fu_452_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Tm_3_1_fu_344_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_476_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln309_7_fu_484_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln309_7_fu_470_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln332_4_fu_498_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln332_3_fu_492_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln323_2_fu_510_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_fu_540_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln309_8_fu_548_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln309_8_fu_534_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Tm_2_2_fu_522_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln329_7_fu_562_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln329_6_fu_556_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Tm_1_2_fu_516_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_9_fu_580_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln309_9_fu_588_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln309_9_fu_574_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln330_7_fu_602_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln330_6_fu_596_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_10_fu_620_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln309_10_fu_628_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln309_10_fu_614_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln331_7_fu_642_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln331_6_fu_636_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Tm_3_2_fu_528_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_fu_660_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln309_11_fu_668_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln309_11_fu_654_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln332_7_fu_682_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln332_6_fu_676_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln323_3_fu_694_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_12_fu_724_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln309_12_fu_732_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln309_12_fu_718_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Tm_2_3_fu_706_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln329_10_fu_746_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln329_9_fu_740_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Tm_1_3_fu_700_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_13_fu_764_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln309_13_fu_772_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln309_13_fu_758_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln330_10_fu_786_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln330_9_fu_780_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_14_fu_804_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln309_14_fu_812_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln309_14_fu_798_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln331_10_fu_826_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln331_9_fu_820_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Tm_3_3_fu_712_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_15_fu_844_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln309_15_fu_852_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln309_15_fu_838_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln332_10_fu_866_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln332_9_fu_860_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln329_2_fu_200_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln330_2_fu_240_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln331_2_fu_280_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln332_2_fu_320_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln329_5_fu_384_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln330_5_fu_424_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln331_5_fu_464_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln332_5_fu_504_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln329_8_fu_568_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln330_8_fu_608_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln331_8_fu_648_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln332_8_fu_688_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln329_11_fu_752_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln330_11_fu_792_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln331_11_fu_832_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln332_11_fu_872_p2 : STD_LOGIC_VECTOR (7 downto 0);


begin



    Tm_1_1_fu_332_p2 <= (state_1_2_read xor state_1_1_read);
    Tm_1_2_fu_516_p2 <= (state_2_2_read xor state_2_1_read);
    Tm_1_3_fu_700_p2 <= (state_3_2_read xor state_3_1_read);
    Tm_1_fu_148_p2 <= (state_0_2_read xor state_0_1_read);
    Tm_2_1_fu_338_p2 <= (state_1_3_read xor state_1_2_read);
    Tm_2_2_fu_522_p2 <= (state_2_3_read xor state_2_2_read);
    Tm_2_3_fu_706_p2 <= (state_3_3_read xor state_3_2_read);
    Tm_2_fu_154_p2 <= (state_0_3_read xor state_0_2_read);
    Tm_3_1_fu_344_p2 <= (state_1_3_read xor state_1_0_read);
    Tm_3_2_fu_528_p2 <= (state_2_3_read xor state_2_0_read);
    Tm_3_3_fu_712_p2 <= (state_3_3_read xor state_3_0_read);
    Tm_3_fu_160_p2 <= (state_0_3_read xor state_0_0_read);
    ap_ready <= ap_const_logic_1;
    ap_return_0 <= xor_ln329_2_fu_200_p2;
    ap_return_1 <= xor_ln330_2_fu_240_p2;
    ap_return_10 <= xor_ln331_8_fu_648_p2;
    ap_return_11 <= xor_ln332_8_fu_688_p2;
    ap_return_12 <= xor_ln329_11_fu_752_p2;
    ap_return_13 <= xor_ln330_11_fu_792_p2;
    ap_return_14 <= xor_ln331_11_fu_832_p2;
    ap_return_15 <= xor_ln332_11_fu_872_p2;
    ap_return_2 <= xor_ln331_2_fu_280_p2;
    ap_return_3 <= xor_ln332_2_fu_320_p2;
    ap_return_4 <= xor_ln329_5_fu_384_p2;
    ap_return_5 <= xor_ln330_5_fu_424_p2;
    ap_return_6 <= xor_ln331_5_fu_464_p2;
    ap_return_7 <= xor_ln332_5_fu_504_p2;
    ap_return_8 <= xor_ln329_8_fu_568_p2;
    ap_return_9 <= xor_ln330_8_fu_608_p2;
    select_ln309_10_fu_628_p3 <= 
        ap_const_lv8_1B when (tmp_10_fu_620_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln309_11_fu_668_p3 <= 
        ap_const_lv8_1B when (tmp_11_fu_660_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln309_12_fu_732_p3 <= 
        ap_const_lv8_1B when (tmp_12_fu_724_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln309_13_fu_772_p3 <= 
        ap_const_lv8_1B when (tmp_13_fu_764_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln309_14_fu_812_p3 <= 
        ap_const_lv8_1B when (tmp_14_fu_804_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln309_15_fu_852_p3 <= 
        ap_const_lv8_1B when (tmp_15_fu_844_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln309_1_fu_220_p3 <= 
        ap_const_lv8_1B when (tmp_1_fu_212_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln309_2_fu_260_p3 <= 
        ap_const_lv8_1B when (tmp_2_fu_252_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln309_3_fu_300_p3 <= 
        ap_const_lv8_1B when (tmp_3_fu_292_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln309_4_fu_364_p3 <= 
        ap_const_lv8_1B when (tmp_4_fu_356_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln309_5_fu_404_p3 <= 
        ap_const_lv8_1B when (tmp_5_fu_396_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln309_6_fu_444_p3 <= 
        ap_const_lv8_1B when (tmp_6_fu_436_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln309_7_fu_484_p3 <= 
        ap_const_lv8_1B when (tmp_7_fu_476_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln309_8_fu_548_p3 <= 
        ap_const_lv8_1B when (tmp_8_fu_540_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln309_9_fu_588_p3 <= 
        ap_const_lv8_1B when (tmp_9_fu_580_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln309_fu_180_p3 <= 
        ap_const_lv8_1B when (tmp_fu_172_p3(0) = '1') else 
        ap_const_lv8_0;
    shl_ln309_10_fu_614_p2 <= std_logic_vector(shift_left(unsigned(Tm_2_2_fu_522_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    shl_ln309_11_fu_654_p2 <= std_logic_vector(shift_left(unsigned(Tm_3_2_fu_528_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    shl_ln309_12_fu_718_p2 <= std_logic_vector(shift_left(unsigned(xor_ln323_3_fu_694_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    shl_ln309_13_fu_758_p2 <= std_logic_vector(shift_left(unsigned(Tm_1_3_fu_700_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    shl_ln309_14_fu_798_p2 <= std_logic_vector(shift_left(unsigned(Tm_2_3_fu_706_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    shl_ln309_15_fu_838_p2 <= std_logic_vector(shift_left(unsigned(Tm_3_3_fu_712_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    shl_ln309_1_fu_206_p2 <= std_logic_vector(shift_left(unsigned(Tm_1_fu_148_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    shl_ln309_2_fu_246_p2 <= std_logic_vector(shift_left(unsigned(Tm_2_fu_154_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    shl_ln309_3_fu_286_p2 <= std_logic_vector(shift_left(unsigned(Tm_3_fu_160_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    shl_ln309_4_fu_350_p2 <= std_logic_vector(shift_left(unsigned(xor_ln323_1_fu_326_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    shl_ln309_5_fu_390_p2 <= std_logic_vector(shift_left(unsigned(Tm_1_1_fu_332_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    shl_ln309_6_fu_430_p2 <= std_logic_vector(shift_left(unsigned(Tm_2_1_fu_338_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    shl_ln309_7_fu_470_p2 <= std_logic_vector(shift_left(unsigned(Tm_3_1_fu_344_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    shl_ln309_8_fu_534_p2 <= std_logic_vector(shift_left(unsigned(xor_ln323_2_fu_510_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    shl_ln309_9_fu_574_p2 <= std_logic_vector(shift_left(unsigned(Tm_1_2_fu_516_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    shl_ln309_fu_166_p2 <= std_logic_vector(shift_left(unsigned(xor_ln323_fu_142_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    tmp_10_fu_620_p3 <= Tm_2_2_fu_522_p2(7 downto 7);
    tmp_11_fu_660_p3 <= Tm_3_2_fu_528_p2(7 downto 7);
    tmp_12_fu_724_p3 <= xor_ln323_3_fu_694_p2(7 downto 7);
    tmp_13_fu_764_p3 <= Tm_1_3_fu_700_p2(7 downto 7);
    tmp_14_fu_804_p3 <= Tm_2_3_fu_706_p2(7 downto 7);
    tmp_15_fu_844_p3 <= Tm_3_3_fu_712_p2(7 downto 7);
    tmp_1_fu_212_p3 <= Tm_1_fu_148_p2(7 downto 7);
    tmp_2_fu_252_p3 <= Tm_2_fu_154_p2(7 downto 7);
    tmp_3_fu_292_p3 <= Tm_3_fu_160_p2(7 downto 7);
    tmp_4_fu_356_p3 <= xor_ln323_1_fu_326_p2(7 downto 7);
    tmp_5_fu_396_p3 <= Tm_1_1_fu_332_p2(7 downto 7);
    tmp_6_fu_436_p3 <= Tm_2_1_fu_338_p2(7 downto 7);
    tmp_7_fu_476_p3 <= Tm_3_1_fu_344_p2(7 downto 7);
    tmp_8_fu_540_p3 <= xor_ln323_2_fu_510_p2(7 downto 7);
    tmp_9_fu_580_p3 <= Tm_1_2_fu_516_p2(7 downto 7);
    tmp_fu_172_p3 <= xor_ln323_fu_142_p2(7 downto 7);
    xor_ln323_1_fu_326_p2 <= (state_1_1_read xor state_1_0_read);
    xor_ln323_2_fu_510_p2 <= (state_2_1_read xor state_2_0_read);
    xor_ln323_3_fu_694_p2 <= (state_3_1_read xor state_3_0_read);
    xor_ln323_fu_142_p2 <= (state_0_1_read xor state_0_0_read);
    xor_ln329_10_fu_746_p2 <= (state_3_1_read xor Tm_2_3_fu_706_p2);
    xor_ln329_11_fu_752_p2 <= (xor_ln329_9_fu_740_p2 xor xor_ln329_10_fu_746_p2);
    xor_ln329_1_fu_194_p2 <= (state_0_1_read xor Tm_2_fu_154_p2);
    xor_ln329_2_fu_200_p2 <= (xor_ln329_fu_188_p2 xor xor_ln329_1_fu_194_p2);
    xor_ln329_3_fu_372_p2 <= (shl_ln309_4_fu_350_p2 xor select_ln309_4_fu_364_p3);
    xor_ln329_4_fu_378_p2 <= (state_1_1_read xor Tm_2_1_fu_338_p2);
    xor_ln329_5_fu_384_p2 <= (xor_ln329_4_fu_378_p2 xor xor_ln329_3_fu_372_p2);
    xor_ln329_6_fu_556_p2 <= (shl_ln309_8_fu_534_p2 xor select_ln309_8_fu_548_p3);
    xor_ln329_7_fu_562_p2 <= (state_2_1_read xor Tm_2_2_fu_522_p2);
    xor_ln329_8_fu_568_p2 <= (xor_ln329_7_fu_562_p2 xor xor_ln329_6_fu_556_p2);
    xor_ln329_9_fu_740_p2 <= (shl_ln309_12_fu_718_p2 xor select_ln309_12_fu_732_p3);
    xor_ln329_fu_188_p2 <= (shl_ln309_fu_166_p2 xor select_ln309_fu_180_p3);
    xor_ln330_10_fu_786_p2 <= (state_3_0_read xor Tm_2_3_fu_706_p2);
    xor_ln330_11_fu_792_p2 <= (xor_ln330_9_fu_780_p2 xor xor_ln330_10_fu_786_p2);
    xor_ln330_1_fu_234_p2 <= (state_0_0_read xor Tm_2_fu_154_p2);
    xor_ln330_2_fu_240_p2 <= (xor_ln330_fu_228_p2 xor xor_ln330_1_fu_234_p2);
    xor_ln330_3_fu_412_p2 <= (shl_ln309_5_fu_390_p2 xor select_ln309_5_fu_404_p3);
    xor_ln330_4_fu_418_p2 <= (state_1_0_read xor Tm_2_1_fu_338_p2);
    xor_ln330_5_fu_424_p2 <= (xor_ln330_4_fu_418_p2 xor xor_ln330_3_fu_412_p2);
    xor_ln330_6_fu_596_p2 <= (shl_ln309_9_fu_574_p2 xor select_ln309_9_fu_588_p3);
    xor_ln330_7_fu_602_p2 <= (state_2_0_read xor Tm_2_2_fu_522_p2);
    xor_ln330_8_fu_608_p2 <= (xor_ln330_7_fu_602_p2 xor xor_ln330_6_fu_596_p2);
    xor_ln330_9_fu_780_p2 <= (shl_ln309_13_fu_758_p2 xor select_ln309_13_fu_772_p3);
    xor_ln330_fu_228_p2 <= (shl_ln309_1_fu_206_p2 xor select_ln309_1_fu_220_p3);
    xor_ln331_10_fu_826_p2 <= (xor_ln323_3_fu_694_p2 xor state_3_3_read);
    xor_ln331_11_fu_832_p2 <= (xor_ln331_9_fu_820_p2 xor xor_ln331_10_fu_826_p2);
    xor_ln331_1_fu_274_p2 <= (xor_ln323_fu_142_p2 xor state_0_3_read);
    xor_ln331_2_fu_280_p2 <= (xor_ln331_fu_268_p2 xor xor_ln331_1_fu_274_p2);
    xor_ln331_3_fu_452_p2 <= (shl_ln309_6_fu_430_p2 xor select_ln309_6_fu_444_p3);
    xor_ln331_4_fu_458_p2 <= (xor_ln323_1_fu_326_p2 xor state_1_3_read);
    xor_ln331_5_fu_464_p2 <= (xor_ln331_4_fu_458_p2 xor xor_ln331_3_fu_452_p2);
    xor_ln331_6_fu_636_p2 <= (shl_ln309_10_fu_614_p2 xor select_ln309_10_fu_628_p3);
    xor_ln331_7_fu_642_p2 <= (xor_ln323_2_fu_510_p2 xor state_2_3_read);
    xor_ln331_8_fu_648_p2 <= (xor_ln331_7_fu_642_p2 xor xor_ln331_6_fu_636_p2);
    xor_ln331_9_fu_820_p2 <= (shl_ln309_14_fu_798_p2 xor select_ln309_14_fu_812_p3);
    xor_ln331_fu_268_p2 <= (shl_ln309_2_fu_246_p2 xor select_ln309_2_fu_260_p3);
    xor_ln332_10_fu_866_p2 <= (xor_ln323_3_fu_694_p2 xor state_3_2_read);
    xor_ln332_11_fu_872_p2 <= (xor_ln332_9_fu_860_p2 xor xor_ln332_10_fu_866_p2);
    xor_ln332_1_fu_314_p2 <= (xor_ln323_fu_142_p2 xor state_0_2_read);
    xor_ln332_2_fu_320_p2 <= (xor_ln332_fu_308_p2 xor xor_ln332_1_fu_314_p2);
    xor_ln332_3_fu_492_p2 <= (shl_ln309_7_fu_470_p2 xor select_ln309_7_fu_484_p3);
    xor_ln332_4_fu_498_p2 <= (xor_ln323_1_fu_326_p2 xor state_1_2_read);
    xor_ln332_5_fu_504_p2 <= (xor_ln332_4_fu_498_p2 xor xor_ln332_3_fu_492_p2);
    xor_ln332_6_fu_676_p2 <= (shl_ln309_11_fu_654_p2 xor select_ln309_11_fu_668_p3);
    xor_ln332_7_fu_682_p2 <= (xor_ln323_2_fu_510_p2 xor state_2_2_read);
    xor_ln332_8_fu_688_p2 <= (xor_ln332_7_fu_682_p2 xor xor_ln332_6_fu_676_p2);
    xor_ln332_9_fu_860_p2 <= (shl_ln309_15_fu_838_p2 xor select_ln309_15_fu_852_p3);
    xor_ln332_fu_308_p2 <= (shl_ln309_3_fu_286_p2 xor select_ln309_3_fu_300_p3);
end behav;
